/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    formation: Formation;
    sectors: Sector;
    chapels: Chapel;
    groups: Group;
    events: Event;
    'radio-programs': RadioProgram;
    'radio-episodes': RadioEpisode;
    'prayer-requests': PrayerRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    formation: FormationSelect<false> | FormationSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    chapels: ChapelsSelect<false> | ChapelsSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'radio-programs': RadioProgramsSelect<false> | RadioProgramsSelect<true>;
    'radio-episodes': RadioEpisodesSelect<false> | RadioEpisodesSelect<true>;
    'prayer-requests': PrayerRequestsSelect<false> | PrayerRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    contact: Contact;
    settings: Setting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'super-admin' | 'contenido' | 'comunicaciones';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Texto alternativo. Obligatorio por accesibilidad.
   */
  alt: string;
  caption?: string | null;
  /**
   * Fotógrafo o fuente, si corresponde.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Identificador para la URL. Solo minusculas, numeros y guiones.
   */
  slug: string;
  /**
   * Resumen corto para listados y redes.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('aviso' | 'comunicado' | 'celebracion' | 'pastoral' | 'emergencia') | null;
  cover?: (number | null) | Media;
  /**
   * Destacar en la home.
   */
  isFeatured?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Fecha que se muestra al publico.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formation".
 */
export interface Formation {
  id: number;
  title: string;
  /**
   * Identificador para la URL. Solo minusculas, numeros y guiones.
   */
  slug: string;
  /**
   * Resumen corto para el listado.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('serie' | 'recurso' | 'articulo' | 'catequesis') | null;
  audience?: ('jovenes' | 'familias' | 'servidores' | 'general') | null;
  cover?: (number | null) | Media;
  resourceFile?: (number | null) | Media;
  isFeatured?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Fecha que se muestra al publico.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  name: string;
  /**
   * Identificador para la URL. Solo minusculas, numeros y guiones.
   */
  slug: string;
  number?: number | null;
  chapelName?: string | null;
  /**
   * Texto corto para las tarjetas del listado.
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  history?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Dónde queda. Las coordenadas alimentan el mapa.
   */
  location?: {
    address?: string | null;
    /**
     * Longitud, latitud.
     *
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
  };
  responsibleName?: string | null;
  assistants?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Datos de contacto. Todos opcionales.
   */
  contact?: {
    phone?: string | null;
    whatsapp?: string | null;
    email?: string | null;
    /**
     * Facebook, YouTube, Instagram, etc.
     */
    socialLinks?:
      | {
          platform?: ('facebook' | 'youtube' | 'instagram' | 'whatsapp' | 'otro') | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cover?: (number | null) | Media;
  /**
   * Destacar en la home.
   */
  isFeatured?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Fecha que se muestra al publico.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapels".
 */
export interface Chapel {
  id: number;
  name: string;
  /**
   * Identificador para la URL. Solo minusculas, numeros y guiones.
   */
  slug: string;
  sector: number | Sector;
  patronOrDedication?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Una línea por horario.
   */
  massSchedule?: string | null;
  /**
   * Dónde queda. Las coordenadas alimentan el mapa.
   */
  location?: {
    address?: string | null;
    /**
     * Longitud, latitud.
     *
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
  };
  cover?: (number | null) | Media;
  status: 'draft' | 'published' | 'archived';
  /**
   * Fecha que se muestra al publico.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  /**
   * Identificador para la URL. Solo minusculas, numeros y guiones.
   */
  slug: string;
  type?: ('pastoral' | 'ministerio' | 'comunidad' | 'servicio' | 'formacion') | null;
  /**
   * Texto corto para las tarjetas del listado.
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meeting?: {
    day?: string | null;
    time?: string | null;
    place?: string | null;
  };
  /**
   * Qué hacer para integrarse al grupo.
   */
  howToJoin?: string | null;
  coordinatorName?: string | null;
  /**
   * Datos de contacto. Todos opcionales.
   */
  contact?: {
    phone?: string | null;
    whatsapp?: string | null;
    email?: string | null;
    /**
     * Facebook, YouTube, Instagram, etc.
     */
    socialLinks?:
      | {
          platform?: ('facebook' | 'youtube' | 'instagram' | 'whatsapp' | 'otro') | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cover?: (number | null) | Media;
  /**
   * Destacar en la home.
   */
  isFeatured?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Fecha que se muestra al publico.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Identificador para la URL. Solo minusculas, numeros y guiones.
   */
  slug: string;
  eventType?:
    | (
        | 'misa'
        | 'vigilia'
        | 'hora-santa'
        | 'jornada'
        | 'reunion'
        | 'novena'
        | 'retiro'
        | 'sector'
        | 'grupo'
        | 'patronal'
      )
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startsAt: string;
  endsAt?: string | null;
  locationName: string;
  sector?: (number | null) | Sector;
  group?: (number | null) | Group;
  cover?: (number | null) | Media;
  /**
   * Destacar en la home.
   */
  isFeatured?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Fecha que se muestra al publico.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radio-programs".
 */
export interface RadioProgram {
  id: number;
  title: string;
  /**
   * Identificador para la URL. Solo minusculas, numeros y guiones.
   */
  slug: string;
  description?: string | null;
  hostName?: string | null;
  dayOfWeek?: ('lunes' | 'martes' | 'miercoles' | 'jueves' | 'viernes' | 'sabado' | 'domingo' | 'diario') | null;
  startTime?: string | null;
  endTime?: string | null;
  cover?: (number | null) | Media;
  status: 'draft' | 'published' | 'archived';
  /**
   * Fecha que se muestra al publico.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radio-episodes".
 */
export interface RadioEpisode {
  id: number;
  title: string;
  /**
   * Identificador para la URL. Solo minusculas, numeros y guiones.
   */
  slug: string;
  program: number | RadioProgram;
  description?: string | null;
  audioUrl?: string | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Fecha que se muestra al publico.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests".
 */
export interface PrayerRequest {
  id: number;
  name?: string | null;
  contact?: string | null;
  message: string;
  intentionType?: ('general' | 'salud' | 'difuntos' | 'accion-gracias' | 'familia') | null;
  status?: ('pendiente' | 'revisada' | 'orada') | null;
  /**
   * Solo si la persona autorizó que se lea al aire.
   */
  allowPublicMention?: boolean | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'formation';
        value: number | Formation;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'chapels';
        value: number | Chapel;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'radio-programs';
        value: number | RadioProgram;
      } | null)
    | ({
        relationTo: 'radio-episodes';
        value: number | RadioEpisode;
      } | null)
    | ({
        relationTo: 'prayer-requests';
        value: number | PrayerRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  category?: T;
  cover?: T;
  isFeatured?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formation_select".
 */
export interface FormationSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  category?: T;
  audience?: T;
  cover?: T;
  resourceFile?: T;
  isFeatured?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  number?: T;
  chapelName?: T;
  summary?: T;
  description?: T;
  history?: T;
  location?:
    | T
    | {
        address?: T;
        coordinates?: T;
      };
  responsibleName?: T;
  assistants?:
    | T
    | {
        name?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        whatsapp?: T;
        email?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  cover?: T;
  isFeatured?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapels_select".
 */
export interface ChapelsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sector?: T;
  patronOrDedication?: T;
  description?: T;
  massSchedule?: T;
  location?:
    | T
    | {
        address?: T;
        coordinates?: T;
      };
  cover?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  summary?: T;
  description?: T;
  meeting?:
    | T
    | {
        day?: T;
        time?: T;
        place?: T;
      };
  howToJoin?: T;
  coordinatorName?: T;
  contact?:
    | T
    | {
        phone?: T;
        whatsapp?: T;
        email?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  cover?: T;
  isFeatured?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eventType?: T;
  description?: T;
  startsAt?: T;
  endsAt?: T;
  locationName?: T;
  sector?: T;
  group?: T;
  cover?: T;
  isFeatured?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radio-programs_select".
 */
export interface RadioProgramsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  hostName?: T;
  dayOfWeek?: T;
  startTime?: T;
  endTime?: T;
  cover?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radio-episodes_select".
 */
export interface RadioEpisodesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  program?: T;
  description?: T;
  audioUrl?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests_select".
 */
export interface PrayerRequestsSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  message?: T;
  intentionType?: T;
  status?: T;
  allowPublicMention?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero?: {
    title?: string | null;
    subtitle?: string | null;
    image?: (number | null) | Media;
    stats?:
      | {
          number?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * El evento que se muestra en la portada.
   */
  featuredEvent?: (number | null) | Event;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  parishName?: string | null;
  address?: string | null;
  /**
   * Pegá el enlace de "Compartir" de Google Maps. Alimenta el botón "Cómo llegar".
   */
  mapUrl?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  officeHours?:
    | {
        label?: string | null;
        hours?: string | null;
        id?: string | null;
      }[]
    | null;
  channels?:
    | {
        platform?: ('whatsapp' | 'facebook' | 'youtube' | 'instagram') | null;
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  radio?: {
    /**
     * Si esta apagado, la web muestra la radio como "Fuera del aire" y deshabilita el play.
     */
    available?: boolean | null;
    /**
     * Enlace directo al audio (Icecast/HLS). El reproductor lo usa para transmitir en vivo.
     */
    streamUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
        stats?:
          | T
          | {
              number?: T;
              label?: T;
              id?: T;
            };
      };
  featuredEvent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  parishName?: T;
  address?: T;
  mapUrl?: T;
  coordinates?: T;
  officeHours?:
    | T
    | {
        label?: T;
        hours?: T;
        id?: T;
      };
  channels?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  radio?:
    | T
    | {
        available?: T;
        streamUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}